import logging
import uuid

import grpc
from grpc import aio
from schemas.book import BookCreate, BookUpdate, ReservationCreate
from services.book_service import BookService

logger = logging.getLogger("api-lab.grpc")

# These would be generated by Bazel proto_library + grpc_py_library from library.proto
# For local development, we provide a manual implementation
# TODO: Wire up Bazel-generated stubs once proto build targets are configured


class LibraryServiceServicer:
    """gRPC servicer wrapping BookService."""

    def __init__(self, book_service: BookService):
        self._service = book_service

    async def ListBooks(self, request, _context):
        books = await self._service.list_books(
            available_only=request.available_only,
            genre=request.genre or None,
            author=request.author or None,
            search=request.search or None,
        )
        return {"books": [self._book_to_dict(b) for b in books]}

    async def GetBook(self, request, context):
        book = await self._service.get_book(uuid.UUID(request.book_id))
        if not book:
            context.abort(grpc.StatusCode.NOT_FOUND, "Book not found")
        return self._book_to_dict(book)

    async def CreateBook(self, request, _context):
        data = BookCreate(
            isbn=request.isbn,
            title=request.title,
            author=request.author,
            genre=request.genre,
            published_year=request.published_year,
            total_copies=request.total_copies,
        )
        book = await self._service.create_book(data)
        return self._book_to_dict(book)

    async def UpdateBook(self, request, context):
        data = BookUpdate()
        if request.HasField("isbn"):
            data.isbn = request.isbn
        if request.HasField("title"):
            data.title = request.title
        if request.HasField("author"):
            data.author = request.author
        if request.HasField("genre"):
            data.genre = request.genre
        if request.HasField("published_year"):
            data.published_year = request.published_year
        if request.HasField("total_copies"):
            data.total_copies = request.total_copies
        book = await self._service.update_book(uuid.UUID(request.book_id), data)
        if not book:
            context.abort(grpc.StatusCode.NOT_FOUND, "Book not found")
        return self._book_to_dict(book)

    async def DeleteBook(self, request, context):
        deleted = await self._service.delete_book(uuid.UUID(request.book_id))
        if not deleted:
            context.abort(grpc.StatusCode.NOT_FOUND, "Book not found")
        return {}

    async def GetInventory(self, _request, _context):
        books = await self._service.get_inventory()
        return {"books": [self._book_to_dict(b) for b in books]}

    async def ReserveBooks(self, request, context):
        try:
            data = ReservationCreate(
                user_id=request.user_id,
                book_ids=[uuid.UUID(bid) for bid in request.book_ids],
            )
            reservations = await self._service.reserve_books(data)
            return {"reservations": [self._reservation_to_dict(r) for r in reservations]}
        except ValueError as e:
            context.abort(grpc.StatusCode.FAILED_PRECONDITION, str(e))
            return None

    async def ReturnReservation(self, request, context):
        try:
            reservation = await self._service.return_reservation(uuid.UUID(request.reservation_id))
            if not reservation:
                context.abort(grpc.StatusCode.NOT_FOUND, "Reservation not found")
            return self._reservation_to_dict(reservation)
        except ValueError as e:
            context.abort(grpc.StatusCode.FAILED_PRECONDITION, str(e))
            return None

    async def ListReservations(self, request, _context):
        reservations = await self._service.list_reservations(
            user_id=request.user_id or None,
            status=request.status or None,
            book_id=uuid.UUID(request.book_id) if request.book_id else None,
        )
        return {"reservations": [self._reservation_to_dict(r) for r in reservations]}

    async def GetReservation(self, request, context):
        reservation = await self._service.get_reservation(uuid.UUID(request.reservation_id))
        if not reservation:
            context.abort(grpc.StatusCode.NOT_FOUND, "Reservation not found")
        return self._reservation_to_dict(reservation)

    @staticmethod
    def _book_to_dict(book):
        return {
            "id": str(book.id),
            "isbn": book.isbn,
            "title": book.title,
            "author": book.author,
            "genre": book.genre,
            "published_year": book.published_year,
            "total_copies": book.total_copies,
            "available_copies": book.available_copies,
            "created_at": str(book.created_at),
            "updated_at": str(book.updated_at),
        }

    @staticmethod
    def _reservation_to_dict(reservation):
        return {
            "id": str(reservation.id),
            "book_id": str(reservation.book_id),
            "user_id": reservation.user_id,
            "reserved_at": str(reservation.reserved_at),
            "due_date": str(reservation.due_date),
            "returned_at": str(reservation.returned_at) if reservation.returned_at else None,
            "status": reservation.status,
        }


async def start_grpc_server(book_service: BookService, port: int = 50051):
    """Start gRPC server. Uses manual servicer until Bazel proto stubs are wired up."""
    server = aio.server()
    _servicer = LibraryServiceServicer(book_service)
    # TODO: Register with generated pb2_grpc once proto build targets are configured
    logger.info("gRPC server configured on port %d (stub registration pending proto build)", port)

    from grpc_reflection.v1alpha import reflection

    SERVICE_NAMES = ("library.v1.LibraryService",)
    reflection.enable_server_reflection(SERVICE_NAMES, server)

    server.add_insecure_port(f"[::]:{port}")
    await server.start()
    logger.info("gRPC server started on port %d", port)
    return server
