apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  labels:
    component: go-api
data:
  ENVIRONMENT: dev
  APP: api-lab
  COMPONENT: go-api
  APP_VERSION: dev
  COMPONENT_VERSION: latest
  GIT_TAG: latest
  GIT_COMMIT: latest
  LOG_LEVEL: DEBUG
