apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-gateway-config
  labels:
    component: graphql-gateway
data:
  ENVIRONMENT: dev
  APP: api-lab
  COMPONENT: graphql-gateway
  APP_VERSION: dev
  COMPONENT_VERSION: latest
  GIT_TAG: api-lab/graphql-gateway/latest
  GIT_COMMIT: latest
  LOG_LEVEL: DEBUG
  REST_API_URL: http://python-api.playground-apps-dev-api-lab.svc.cluster.local:8080
  ENABLE_TRACING: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
