apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: graphql-gateway
  labels:
    app: api-lab
    component: graphql-gateway
    environment: dev
    release: monitoring
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: api-lab
      component: graphql-gateway
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  podTargetLabels:
  - app
  - component
  - environment
  namespaceSelector:
    matchNames:
    - playground-apps-dev-api-lab
