apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: graphql-gateway-allow-egress
  labels:
    app: api-lab
    component: graphql-gateway
    environment: dev
spec:
  podSelector:
    matchLabels:
      component: graphql-gateway
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          component: python-api
    ports:
    - protocol: TCP
      port: 8080
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: 4317
    - protocol: TCP
      port: 4318
