apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: python-auth-api-allow-egress
  labels:
    app: api-lab
    component: python-auth-api
    environment: dev
spec:
  podSelector:
    matchLabels:
      component: python-auth-api
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  - to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/part-of: playground-infra
          environment: dev
    ports:
    - protocol: TCP
      port: 5432
    - protocol: TCP
      port: 6379
    - protocol: TCP
      port: 8080
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: 4317
    - protocol: TCP
      port: 4318
  - to:
    - podSelector: {}
