apiVersion: v1
kind: ConfigMap
metadata:
  name: python-grpc-api-config
  labels:
    component: python-grpc-api
data:
  ENVIRONMENT: dev
  APP: api-lab
  COMPONENT: python-grpc-api
  APP_VERSION: dev
  COMPONENT_VERSION: latest
  GIT_TAG: api-lab/python-grpc-api/latest
  GIT_COMMIT: latest
  LOG_LEVEL: DEBUG
  POSTGRES_HOST: postgres.playground-infra-dev.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: playground
  POSTGRES_USER: playground-dev
  REDIS_HOST: redis.playground-infra-dev.svc.cluster.local
  REDIS_PORT: "6379"
  GRPC_PORT: "50051"
  ENABLE_TRACING: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
