apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: python-api-credentials
  namespace: playground-apps-dev-api-lab
spec:
  encryptedData:
    POSTGRES_PASSWORD: PLACEHOLDER_SEALED_SECRET
    REDIS_PASSWORD: PLACEHOLDER_SEALED_SECRET
  template:
    metadata:
      name: python-api-credentials
      namespace: playground-apps-dev-api-lab
    type: Opaque
