apiVersion: v1
kind: ConfigMap
metadata:
  name: rust-traffic-generator-config
  labels:
    component: rust-traffic-generator
data:
  ENVIRONMENT: dev
  APP: api-lab
  COMPONENT: rust-traffic-generator
  LOG_LEVEL: DEBUG
  PYTHON_API_URL: http://python-api:8080
  CONCURRENCY: "10"
  REQUEST_INTERVAL_MS: "1000"
