apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator-service
spec:
  replicas: 1
  template:
    spec:
      affinity:
        $patch: replace
      securityContext:
        $patch: replace
      containers:
      - name: traffic-generator-service
        image: traffic-generator-service:latest
        imagePullPolicy: Never
        securityContext:
          $patch: replace
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
