apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator-service
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: traffic-generator-service
        image: traffic-generator-service:latest
        imagePullPolicy: Never
        command: ["/bin/sh", "-c", "echo STARTING; /usr/local/bin/python /app/src/main.py; echo FINISHED $?"]
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
