apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-service-config
  labels:
    app: demo-app
    component: traffic-generator-service
    environment: sandbox
data:
  ENVIRONMENT: sandbox
  APP: demo-app
  COMPONENT: traffic-generator-service
  LOG_LEVEL: INFO
  APP_VERSION: sandbox
  COMPONENT_VERSION: unknown
  GIT_TAG: unknown
  GIT_COMMIT: unknown
  TARGET_URL: http://greeting-service
  CONCURRENCY: "10"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
  ENABLE_TRACING: "true"
