apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-grpc-api
  labels:
    component: python-grpc-api
    app: api-lab
    environment: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      component: python-grpc-api
  template:
    metadata:
      labels:
        component: python-grpc-api
        app: api-lab
        environment: sandbox
    spec:
      containers:
        - name: python-grpc-api
          image: nexus.gillouche.homelab/docker-hosted/api-lab/python-grpc-api
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: python-grpc-api-config
            - secretRef:
                name: python-grpc-api-secrets
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 50051
              name: grpc
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
          readinessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 10
