apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-check-service-config
data:
  ENVIRONMENT: sandbox
  LOG_LEVEL: DEBUG
  POSTGRES_HOST: postgres.default.svc.cluster.local
  REDIS_HOST: redis.default.svc.cluster.local
  KAFKA_BOOTSTRAP_SERVERS: kafka.default.svc.cluster.local:9092
  MONGODB_HOST: mongodb.default.svc.cluster.local
