apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Override base image with local image for dev
images:
  - name: nexus.gillouche.homelab/repository/docker-all/playground/demo-concept
    newName: py-app
    newTag: latest

patches:
  - path: patches.yaml
