bazel_dep(name = "rules_python", version = "1.8.0")
bazel_dep(name = "rules_oci", version = "2.2.7")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "platforms", version = "1.0.0")

python = use_extension("@rules_python//python/extensions:python.bzl", "python")
python.toolchain(
    python_version = "3.12",
)
use_repo(python, "python_3_12")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "python_base",
    image = "gcr.io/distroless/python3-debian12",
    platforms = [
        "linux/amd64",
        "linux/arm64",
    ],
    digest = "sha256:17b27c84c985a53d0cd2adef4f196ca327fa9b6755369be605cf45533b4e700b",
)
use_repo(oci, "python_base", "python_base_linux_arm64", "python_base_linux_amd64")
