package(default_visibility = ["//visibility:public"])

exports_files([
    "run_command.sh",
    "build_docker.sh",
    "deploy_minikube.sh",
    "dev_workflow.sh",
    "smart_push.sh",
    "promote_test.py",
    "release_test.py",
    "promote_prod.py",
])

py_binary(
    name = "promote_test",
    srcs = ["promote_test.py"],
)

py_binary(
    name = "release_test",
    srcs = ["release_test.py"],
)

py_binary(
    name = "promote_prod",
    srcs = ["promote_prod.py"],
)
