package(default_visibility = ["//visibility:public"])

exports_files([
    "run_command.sh",
    "build_docker.sh",
    "deploy_minikube.sh",
    "sandbox_workflow.sh",
    "smart_push.sh",
    "promote_test.py",
    "release_test.py",
    "promote_prod.py",
    "sync_dev.py",
    "rollback.py",
    "ytt_gen.sh",
])

py_binary(
    name = "promote_test",
    srcs = ["promote_test.py"],
)

py_binary(
    name = "release_test",
    srcs = ["release_test.py"],
)

py_binary(
    name = "promote_prod",
    srcs = ["promote_prod.py"],
)

py_binary(
    name = "sync_dev",
    srcs = ["sync_dev.py"],
)

py_binary(
    name = "rollback",
    srcs = ["rollback.py"],
)
