package(default_visibility = ["//visibility:public"])

exports_files([
    "run_command.sh",
    "build_docker.sh",
    "deploy_minikube.sh",
    "sandbox_workflow.sh",
    "smart_push.sh",
    "promote_test.py",
    "release_test.py",
    "promote_prod.py",
    "sync_dev.py",
    "rollback.py",
    "ytt_gen.sh",
    "deploy_dev.sh",
    "deploy_test.sh",
    "deploy_prod.sh",
])

py_binary(
    name = "freeze",
    srcs = ["freeze.py"],
)

py_binary(
    name = "promote",
    srcs = ["promote.py"],
)

py_binary(
    name = "sync_dev",
    srcs = ["sync_dev.py"],
)

py_binary(
    name = "rollback",
    srcs = ["rollback.py"],
)

sh_binary(
    name = "smart_push",
    srcs = ["smart_push.sh"],
    data = ["determine_base_commit.py"],
)
