apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Override base image with local image for dev
images:
  - name: nexus.gillouche.homelab/docker-hosted/demo-concept/py-app
    newName: py-app
    newTag: sandbox-1769218223
patches:
  - path: patch-pull-policy.yaml
  - path: patches.yaml
