apiVersion: v1
kind: Secret
metadata:
  name: python-auth-api-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: playground
  REDIS_PASSWORD: playground
  KEYCLOAK_CLIENT_SECRET: api-lab-secret
  KEYCLOAK_AUTH_SERVICE_CLIENT_SECRET: api-lab-auth-service-secret
