apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-auth-api
  labels:
    component: python-auth-api
    app: api-lab
    environment: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      component: python-auth-api
  template:
    metadata:
      labels:
        component: python-auth-api
        app: api-lab
        environment: sandbox
    spec:
      containers:
        - name: python-auth-api
          image: nexus.gillouche.homelab/docker-hosted/api-lab/python-auth-api
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: python-auth-api-config
            - secretRef:
                name: python-auth-api-secrets
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
          ports:
            - containerPort: 8084
              name: http
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1Gi
              cpu: 500m
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
