apiVersion: v1
kind: ConfigMap
metadata:
  name: rust-traffic-generator-config
  labels:
    component: rust-traffic-generator
data:
  ENVIRONMENT: base
  APP: api-lab
  COMPONENT: rust-traffic-generator
  LOG_LEVEL: INFO
  PYTHON_API_URL: http://python-api:8080
  GO_API_URL: http://go-api:8080
  TS_API_URL: http://ts-api:8080
  CONCURRENCY: "5"
  REQUEST_INTERVAL_MS: "1000"
