apiVersion: v1
kind: Service
metadata:
  name: ts-api
spec:
  selector:
    component: ts-api
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
