apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-gateway-config
  labels:
    component: graphql-gateway
data:
  ENVIRONMENT: sandbox
  APP: api-lab
  COMPONENT: graphql-gateway
  APP_VERSION: sandbox
  COMPONENT_VERSION: latest
  GIT_TAG: local/graphql-gateway/latest
  GIT_COMMIT: local
  LOG_LEVEL: DEBUG
  REST_API_URL: http://python-api:8080
