resources:
  - service.yaml
  - configmap.yaml
images:
  - name: nexus.gillouche.homelab/docker-hosted/api-lab/python-api
    newName: nexus.gillouche.homelab/docker-hosted/api-lab/python-api
    newTag: latest
labels:
  - pairs:
      component: python-api
    includeSelectors: false
    includeTemplates: true
