#@ load("@ytt:data", "data")

#@ def get_host(service):
#@   return service + ".playground-infra-" + data.values.env + ".svc.cluster.local"
#@ end

apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-check-service-config
  labels:
    component: infra-check-service
data:
  ENVIRONMENT: #@ data.values.env
  APP: #@ data.values.app
  COMPONENT: #@ data.values.component
  APP_VERSION: #@ data.values.app_version
  COMPONENT_VERSION: #@ data.values.component_version
  GIT_TAG: #@ data.values.git_tag
  GIT_COMMIT: #@ data.values.git_commit
  LOG_LEVEL: INFO
  POSTGRES_HOST: #@ get_host("postgres")
  POSTGRES_PORT: "5432"
  POSTGRES_DB: playground
  POSTGRES_USER: playground
  REDIS_HOST: #@ get_host("redis")
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: #@ get_host("kafka") + ":9092"
  KAFKA_TOPIC: infra-check
  MONGODB_HOST: #@ get_host("mongodb")
  MONGODB_PORT: "27017"
  MONGODB_DB: playground
  MONGODB_USER: playground
