apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../py-app/deploy/base

metadata:
  name: py-app

labels:
  - pairs:
      concept: demo-concept
    includeSelectors: false

commonAnnotations:
  owner: gillouche
