apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-service-config
  labels:
    app: demo-app
    component: greeting-service
    environment: prod
data:
  ENVIRONMENT: prod
  APP: demo-app
  COMPONENT: greeting-service
  LOG_LEVEL: INFO
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
  ENABLE_TRACING: "true"
  APP_VERSION: v0.0.9
  COMPONENT_VERSION: v0.0.7
  GIT_TAG: demo-app/greeting-service/v0.0.7
  GIT_COMMIT: c333c4d12aaba4448a7361041bec11bce30e8f2d
