apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-service-config
  labels:
    app: demo-app
    component: greeting-service
    environment: prod
data:
  ENVIRONMENT: prod
  APP: demo-app
  COMPONENT: greeting-service
  LOG_LEVEL: INFO
  APP_VERSION: v0.0.3
  GIT_TAG: demo-app/greeting-service/v0.0.3
  GIT_COMMIT: 3ae8cd157163b358a4fc37d8c7f36a083b62ceb5
