apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: greeting-service
  labels:
    component: greeting-service
    app: demo-app
    environment: prod
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: greeting-service
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://monitoring-kube-prometheus-prometheus.monitoring:9090
      metricName: http_requests_per_second
      query: sum(rate(http_requests_total{component="greeting-service"}[2m]))
      threshold: "100"
