apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-check-service-config
  labels:
    component: infra-check-service
data:
  ENVIRONMENT: prod
  APP: demo-app
  COMPONENT: infra-check-service
  APP_VERSION: v0.0.9
  COMPONENT_VERSION: v0.0.5
  GIT_TAG: demo-app/infra-check-service/v0.0.5
  GIT_COMMIT: c333c4d12aaba4448a7361041bec11bce30e8f2d
  LOG_LEVEL: INFO
  POSTGRES_HOST: postgres.playground-infra-prod.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: playground
  POSTGRES_USER: playground
  REDIS_HOST: redis.playground-infra-prod.svc.cluster.local
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka.playground-infra-prod.svc.cluster.local:9092
  KAFKA_TOPIC: infra-check
  MONGODB_HOST: mongodb.playground-infra-prod.svc.cluster.local
  MONGODB_PORT: "27017"
  MONGODB_DB: playground
  MONGODB_USER: playground
