apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-check-service-config
data:
  ENVIRONMENT: prod
  LOG_LEVEL: WARNING
  POSTGRES_HOST: postgres.playground-infra-prod.svc.cluster.local
  REDIS_HOST: redis.playground-infra-prod.svc.cluster.local
  KAFKA_BOOTSTRAP_SERVERS: kafka.playground-infra-prod.svc.cluster.local:9092
  MONGODB_HOST: mongodb.playground-infra-prod.svc.cluster.local
