apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: infra-check-service
  labels:
    app: demo-app
    component: infra-check-service
    environment: prod
    release: monitoring
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: demo-app
      component: infra-check-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  podTargetLabels:
  - app
  - component
  - environment
  namespaceSelector:
    matchNames:
    - playground-apps-prod-demo-app
