apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-service-config
  labels:
    app: demo-app
    component: traffic-generator-service
    environment: prod
data:
  ENVIRONMENT: prod
  APP: demo-app
  COMPONENT: traffic-generator-service
  LOG_LEVEL: INFO
  APP_VERSION: v0.0.9
  COMPONENT_VERSION: v0.0.1
  GIT_TAG: demo-app/traffic-generator-service/v0.0.1
  GIT_COMMIT: 86eda1b8e99d234e14a1fb97a1afb4ce9d26fed3
  TARGET_URL: http://greeting-service
  CONCURRENCY: "10"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
  ENABLE_TRACING: "true"
