apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-service-config
  labels:
    app: demo-app
    component: traffic-generator-service
    environment: prod
data:
  ENVIRONMENT: prod
  APP: demo-app
  COMPONENT: traffic-generator-service
  LOG_LEVEL: INFO
  APP_VERSION: v0.1.0
  COMPONENT_VERSION: v0.0.2
  GIT_TAG: demo-app/traffic-generator-service/v0.0.2
  GIT_COMMIT: 44ba71b205b4df9d747eb2b1a74790d8da1b57fc
  TARGET_URL: http://greeting-service
  CONCURRENCY: "10"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
  ENABLE_TRACING: "true"
