apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-gateway-config
  labels:
    component: graphql-gateway
data:
  ENVIRONMENT: base
  APP: api-lab
  APP_VERSION: unknown
  COMPONENT: graphql-gateway
  COMPONENT_VERSION: unknown
  GIT_TAG: unknown
  GIT_COMMIT: unknown
  LOG_LEVEL: INFO
