resources:
  - service.yaml
  - configmap.yaml
images:
  - name: nexus.gillouche.homelab/docker-hosted/api-lab/graphql-gateway
    newName: nexus.gillouche.homelab/docker-hosted/api-lab/graphql-gateway
    newTag: latest
labels:
  - pairs:
      component: graphql-gateway
    includeSelectors: false
    includeTemplates: true
