apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../greeting-service/deploy/base
  - allow-ingress-networkpolicy.yaml
  - analysis-template.yaml
  - pdb.yaml

labels:
  - pairs:
      app: demo-app
    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  owner: gillouche
