apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../greeting-service/deploy/base

# metadata:
#   name: demo-app # Optional: Prefix everything? No, services have their own names.

labels:
  - pairs:
      app: demo-app
    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  owner: gillouche
