services:
  postgres:
    image: nexus.gillouche.homelab/docker-hub/library/postgres:18.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: playground
      POSTGRES_PASSWORD: playground
      POSTGRES_DB: playground
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: nexus.gillouche.homelab/docker-hub/library/redis:8-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass playground

  kafka:
    image: nexus.gillouche.homelab/docker-hub/apache/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: sandbox-kafka

  mongodb:
    image: nexus.gillouche.homelab/docker-hub/library/mongo:8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: playground
      MONGO_INITDB_ROOT_PASSWORD: playground
    volumes:
      - mongodb-data:/data/db

volumes:
  postgres-data:
  mongodb-data:
