apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-service-config
  labels:
    app: demo-app
    component: greeting-service
    environment: dev
data:
  ENVIRONMENT: dev
  APP: demo-app
  COMPONENT: greeting-service
  LOG_LEVEL: DEBUG
  APP_VERSION: dev
  COMPONENT_VERSION: c324a59
  GIT_TAG: c324a59
  GIT_COMMIT: c324a59896afa5bccb7167be40202eaaf0c35f50
