apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-service-config
  labels:
    app: demo-app
    component: greeting-service
    environment: dev
data:
  ENVIRONMENT: dev
  APP: demo-app
  COMPONENT: greeting-service
  LOG_LEVEL: DEBUG
  APP_VERSION: dfae21b26594e5b130d2b3ebc0cfc07a7872529d
  GIT_TAG: dfae21b26594e5b130d2b3ebc0cfc07a7872529d
  GIT_COMMIT: dfae21b26594e5b130d2b3ebc0cfc07a7872529d
