apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: greeting-service
  labels:
    component: greeting-service
    app: demo-app
    environment: dev
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: greeting-service
  minReplicaCount: 1
  maxReplicaCount: 1
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
