apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-service-config
  labels:
    app: demo-app
    component: greeting-service
    environment: dev
data:
  ENVIRONMENT: dev
  APP: demo-app
  COMPONENT: greeting-service
  LOG_LEVEL: DEBUG
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
  ENABLE_TRACING: "true"
  APP_VERSION: dev
  COMPONENT_VERSION: 8693faf
  GIT_TAG: demo-app/greeting-service/8693faf
  GIT_COMMIT: 8693faf221d4d5a76fba2a2e6bd46315bf82c4ea
