apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-check-service-config
  labels:
    component: infra-check-service
data:
  ENVIRONMENT: base
  APP: demo-app
  COMPONENT: infra-check-service
  APP_VERSION: 0.0.0
  GIT_TAG: HEAD
  GIT_COMMIT: unknown
  LOG_LEVEL: INFO
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: playground
  POSTGRES_USER: playground
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TOPIC: infra-check
  MONGODB_HOST: mongodb
  MONGODB_PORT: "27017"
  MONGODB_DB: playground
  MONGODB_USER: playground
