apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-check-service-config
  labels:
    component: infra-check-service
data:
  ENVIRONMENT: dev
  APP: demo-app
  COMPONENT: infra-check-service
  APP_VERSION: dev
  COMPONENT_VERSION: 2269718
  GIT_TAG: 2269718
  GIT_COMMIT: 22697180eff7fcbca95d344bddb83316b980cadf
  LOG_LEVEL: INFO
  POSTGRES_HOST: postgres.playground-infra-dev.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: playground
  POSTGRES_USER: playground
  REDIS_HOST: redis.playground-infra-dev.svc.cluster.local
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: kafka.playground-infra-dev.svc.cluster.local:9092
  KAFKA_TOPIC: infra-check
  MONGODB_HOST: mongodb.playground-infra-dev.svc.cluster.local
  MONGODB_PORT: "27017"
  MONGODB_DB: playground
  MONGODB_USER: playground
