apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - greeting-service-ingress.yaml
  - greeting-service-rollout.yaml
  - greeting-service-servicemonitor.yaml
  - ../../infra-check-service/deploy/base
  - infra-check-service-configmap.yaml
  - infra-check-service-ingress.yaml
  - infra-check-service-rollout.yaml
  - infra-check-service-servicemonitor.yaml
  - infra-check-credentials.yaml

patches:
  - path: greeting-service-configmap.yaml
  - path: infra-check-service-configmap.yaml
  - target:
      kind: ConfigMap
      name: demo-app-dashboard
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: demo-app-dashboard
        labels:
          grafana_dashboard: "1"

images:
  - name: nexus.gillouche.homelab/docker-hosted/demo-app/greeting-service
    newTag: 8b2174c
  - name: nexus.gillouche.homelab/docker-hosted/demo-app/infra-check-service
    newTag: 9617f93

labels:
  - pairs:
      environment: dev
      app: demo-app
    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  owner: gillouche
