apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../rollouts-base
  - monitoring-grafana-dashboard.yaml

labels:
  - pairs:
      environment: dev
      app: demo-app
    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  owner: gillouche
