apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-service-config
  labels:
    app: demo-app
    component: traffic-generator-service
    environment: dev
data:
  ENVIRONMENT: dev
  APP: demo-app
  COMPONENT: traffic-generator-service
  LOG_LEVEL: INFO
  APP_VERSION: dev
  COMPONENT_VERSION: 6fd6b0e
  GIT_TAG: demo-app/traffic-generator-service/6fd6b0e
  GIT_COMMIT: 6fd6b0ef80613f067c87145c7e6115121244364a
  TARGET_URL: http://greeting-service
  CONCURRENCY: "10"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
  ENABLE_TRACING: "true"
