apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator-service
spec:
  replicas: 1
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: traffic-generator-service-scaler
spec:
  minReplicaCount: 1
  maxReplicaCount: 1
  triggers:
  - type: cron
    metadata:
      timezone: UTC
      start: "15 * * * *"
      end: "30 * * * *"
      desiredReplicas: "5"
