apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-service-config
  labels:
    app: demo-app
    component: traffic-generator-service
    environment: dev
data:
  ENVIRONMENT: dev
  APP: demo-app
  COMPONENT: traffic-generator-service
  LOG_LEVEL: INFO
  APP_VERSION: dev
  COMPONENT_VERSION: 9697d7e
  GIT_TAG: 9697d7e
  GIT_COMMIT: 9697d7eb1460b70683c7aa0217072c5528bfaa92
  TARGET_URL: http://greeting-service
  CONCURRENCY: "10"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
  ENABLE_TRACING: "true"
