apiVersion: v1
kind: Secret
metadata:
  name: infra-secrets
stringData:
  POSTGRES_PASSWORD: playground
  REDIS_PASSWORD: playground
  MONGODB_PASSWORD: playground
  KEYCLOAK_ADMIN_PASSWORD: playground
