apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  labels:
    component: go-api
data:
  ENVIRONMENT: prod
  APP: api-lab
  COMPONENT: go-api
  APP_VERSION: prod
  COMPONENT_VERSION: v0.0.1
  GIT_TAG: v0.0.1
  GIT_COMMIT: v0.0.1
  LOG_LEVEL: INFO
