apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-api
  labels:
    app: api-lab
    component: python-api
    environment: prod
    release: monitoring
spec:
  jobLabel: component
  selector:
    matchLabels:
      app: api-lab
      component: python-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  podTargetLabels:
    - app
    - component
    - environment
  namespaceSelector:
    matchNames:
      - playground-apps-prod-api-lab
