apiVersion: v1
kind: ConfigMap
metadata:
  name: python-api-config
  labels:
    component: python-api
data:
  ENVIRONMENT: prod
  APP: api-lab
  COMPONENT: python-api
  APP_VERSION: prod
  COMPONENT_VERSION: v0.0.1
  GIT_TAG: v0.0.1
  GIT_COMMIT: v0.0.1
  LOG_LEVEL: INFO
  POSTGRES_HOST: postgres.playground-infra-prod.svc.cluster.local
  POSTGRES_PORT: "5432"
  POSTGRES_DB: api_lab
  POSTGRES_USER: api_lab
  REDIS_HOST: redis.playground-infra-prod.svc.cluster.local
  REDIS_PORT: "6379"
  GRPC_PORT: "50051"
  ENABLE_TRACING: "true"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.monitoring.svc.cluster.local:4317
