apiVersion: v1
kind: ConfigMap
metadata:
  name: go-api-config
  labels:
    component: go-api
data:
  ENVIRONMENT: sandbox
  APP: api-lab
  COMPONENT: go-api
  APP_VERSION: sandbox
  COMPONENT_VERSION: latest
  GIT_TAG: local/go-api/latest
  GIT_COMMIT: local
  LOG_LEVEL: DEBUG
