resources:
  - ../../../go-api/deploy/base
  - go-api-rollout.yaml
patches:
  - path: go-api-configmap.yaml
images:
  - name: nexus.gillouche.homelab/docker-hosted/api-lab/go-api
    newName: go-api
    newTag: latest
labels:
  - pairs:
      environment: sandbox
      app: api-lab
    includeSelectors: false
    includeTemplates: true
