package(default_visibility = ["//visibility:public"])

exports_files([
    "sync_dev.py",
    "rollback.py",
    "freeze.py",
    "promote.py",
    "determine_base_commit.py",
    "package_app.py",
])

py_binary(
    name = "freeze",
    srcs = ["freeze.py"],
)

py_binary(
    name = "promote",
    srcs = ["promote.py"],
)

py_binary(
    name = "sync_dev",
    srcs = ["sync_dev.py"],
    data = ["//:ca-bundle.pem"],
)

py_binary(
    name = "rollback",
    srcs = ["rollback.py"],
)

# Used by smart_push
py_binary(
    name = "determine_base_commit",
    srcs = ["determine_base_commit.py"],
    data = ["//:ca-bundle.pem"],
)
