apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - py-app-ingress.yaml
  - py-app-configmap.yaml
images:
  - name: nexus.gillouche.homelab/docker-hosted/demo-concept/py-app
    newTag: git-426bba9

labels:
  - pairs:
      environment: dev
    includeSelectors: false
