apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: nexus.gillouche.homelab/docker-hosted/demo-concept/py-app
    newTag: git-1991603

labels:
  - pairs:
      environment: dev
    includeSelectors: false
