apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
images:
  - name: nexus.gillouche.homelab/docker-hosted/demo-concept/py-app
    newTag: git-5212504

labels:
  - pairs:
      environment: dev
    includeSelectors: false

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: py-app.demo-concept.dev.k3s.gillouche.homelab
      - op: replace
        path: /spec/tls/0/hosts/0
        value: py-app.demo-concept.dev.k3s.gillouche.homelab
    target:
      kind: Ingress
      name: py-app
