apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-traffic-generator
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: rust-traffic-generator
          image: rust-traffic-generator:latest
          imagePullPolicy: Never
