apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# Image configuration (can be overridden by overlays)
images:
  - name: demo-concept
    newName: nexus.gillouche.homelab/repository/docker-all/playground/demo-concept
    newTag: latest
