apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# Image configuration (can be overridden by overlays)
images:
  - name: py-app
    newName: nexus.gillouche.homelab/docker-hosted/demo-concept/py-app
    newTag: latest
