apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator-service
  labels:
    component: traffic-generator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      component: traffic-generator-service
  template:
    metadata:
      labels:
        component: traffic-generator-service
    spec:
      containers:
      - name: traffic-generator-service
        image: nexus.gillouche.homelab/docker-hosted/demo-app/traffic-generator-service:latest
        imagePullPolicy: Always
        command: ["python", "/app/src/main.py"]
        envFrom:
        - configMapRef:
            name: traffic-generator-service-config
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          capabilities:
            drop:
            - ALL
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/node-group
                operator: In
                values:
                - rpi
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: traffic-generator-service
  labels:
    component: traffic-generator-service
spec:
  selector:
    component: traffic-generator-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
