apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../../greeting-service/deploy/base
  - greeting-service-rollout.yaml

patches:
  - path: greeting-service-configmap.yaml

images:
  - name: nexus.gillouche.homelab/docker-hosted/demo-app/greeting-service
    newName: greeting-service
    newTag: latest

labels:
  - pairs:
      environment: sandbox
      app: demo-app
    includeSelectors: false
    includeTemplates: true

commonAnnotations:
  owner: gillouche
