apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting-service-config
  labels:
    component: greeting-service
data:
  ENVIRONMENT: base
  APP: demo-app
  APP_VERSION: unknown
  COMPONENT: greeting-service
  GIT_TAG: unknown
  GIT_COMMIT: unknown
  LOG_LEVEL: INFO
