apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

# Image configuration (can be overridden by overlays)
images:
  - name: nexus.gillouche.homelab/docker-hosted/demo-app/greeting-service
    newName: nexus.gillouche.homelab/docker-hosted/demo-app/greeting-service
    newTag: latest

labels:
  - pairs:
      component: greeting-service
    includeSelectors: false
