package(default_visibility = ["//visibility:public"])

exports_files([
    "check_go_coverage.sh",
    "notify_discord.sh",
    "smart_push.py",
])

py_binary(
    name = "smart_push",
    srcs = ["smart_push.py"],
    python_version = "PY3",
)

sh_binary(
    name = "check_go_coverage",
    srcs = ["check_go_coverage.sh"],
)

sh_binary(
    name = "notify_discord",
    srcs = ["notify_discord.sh"],
)
