exports_files([
    "defs.bzl",
])

alias(
    name = "promote_test",
    actual = "//tools/scripts:promote_test",
)

alias(
    name = "release_test",
    actual = "//tools/scripts:release_test",
)

alias(
    name = "promote_prod",
    actual = "//tools/scripts:promote_prod",
)

alias(
    name = "release_prod",
    actual = "//tools/scripts:release_prod",
)

alias(
    name = "sync_dev",
    actual = "//tools/scripts:sync_dev",
)

alias(
    name = "rollback",
    actual = "//tools/scripts:rollback",
)

sh_binary(
    name = "gen_manifests",
    srcs = ["//tools/scripts:ytt_gen.sh"],
    tags = ["local"],
)

alias(
    name = "smart_push",
    actual = "//tools/scripts:smart_push",
)
