exports_files([
    "defs.bzl",
])

alias(
    name = "freeze",
    actual = "//tools/scripts/shell:freeze",
)

alias(
    name = "promote",
    actual = "//tools/scripts/shell:promote",
)

alias(
    name = "sync_dev",
    actual = "//tools/scripts/shell:sync_dev",
)

alias(
    name = "rollback",
    actual = "//tools/scripts/shell:rollback",
)

alias(
    name = "gen_manifests",
    actual = "//tools/scripts/shell:gen_manifests",
)

alias(
    name = "smart_push",
    actual = "//tools/scripts/shell:smart_push",
)

alias(
    name = "affected_targets",
    actual = "//tools/scripts/shell:affected_targets",
)


