exports_files([
    "defs.bzl",
])

alias(
    name = "freeze",
    actual = "//tools/scripts/python:freeze",
)

alias(
    name = "promote",
    actual = "//tools/scripts/python:promote",
)

alias(
    name = "sync_dev",
    actual = "//tools/scripts/python:sync_dev",
)

alias(
    name = "rollback",
    actual = "//tools/scripts/python:rollback",
)

alias(
    name = "gen_manifests",
    actual = "//tools/scripts/shell:gen_manifests",
)

alias(
    name = "smart_push",
    actual = "//tools/scripts/shell:smart_push",
)


