#@ load("@ytt:data", "data")

#@ if data.values.env != "sandbox":
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: #@ data.values.component
  labels:
    component: #@ data.values.component
    app: #@ data.values.app
    environment: #@ data.values.env
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: #@ data.values.component
  minReplicaCount: 0
  maxReplicaCount: 0
  pollingInterval: 30
  cooldownPeriod: 300
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "50"
#@ end
