#@ load("@ytt:data", "data")

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: #@ data.values.component
  labels:
    release: monitoring
    app: #@ data.values.app
    component: #@ data.values.component
    environment: #@ data.values.env
spec:
  jobLabel: component
  selector:
    matchLabels:
      component: #@ data.values.component
  #@ if/end hasattr(data.values, "env"):
  namespaceSelector:
    matchNames:
    - #@ "playground-apps-" + data.values.env + "-" + data.values.app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  podTargetLabels:
  - app
  - component
  - environment
